services:
  db:
    image: postgres:16-alpine
    container_name: kanban_db
    environment:
      POSTGRES_USER: kanban
      POSTGRES_PASSWORD: kanban
      POSTGRES_DB: kanban_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: always

  backend:
    build:
      context: ./backend
    container_name: kanban_backend
    env_file:
      - ./backend/.env.docker
    depends_on:
      - db
    ports:
      - "4000:4000"
    restart: always

  frontend:
    build: ./frontend
    container_name: kanban_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend


volumes:
  db_data:
